### PR TITLE
Support Symfony security-bundle 5.0

### PR DESCRIPTION
**Pull request by amharris**
In tune with other dependencies tying in with requirements for first-party 5.x Symfony dependencies, following Symfony 5's release, many—including myself—are in need of the `symfony/security-bundle` 5.0.

From what I quickly tested, this seems to build correctly.
(Note: I've been away from pure Symfony for a _very_ long time, only now revisiting for some big projects, so apologies in advance if there are any additional steps for testing that I should've taken.  Any feedback or suggestions for Symfony and Composer package testing methodologies would be appreciated.)

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 
It is just one more small thing that is blocking. See https://github.com/Happyr/auth0-bundle/blob/master/Security/Authentication/Token/SSOToken.php#L73

We cannot use the `serialize` because it is final in 5.0. 
Is it possible to support 4.4 and 5.0 at the same time?

**Comment by amharris** [comment]
> Thank you for this PR.
> It is just one more small thing that is blocking. See https://github.com/Happyr/auth0-bundle/blob/master/Security/Authentication/Token/SSOToken.php#L73
> 
> We cannot use the `serialize` because it is final in 5.0.
> Is it possible to support 4.4 and 5.0 at the same time?

Thanks for getting back to me.

I'm not 100% sure if I'm to be totally honest with you.  I spent very little time with Symfony 1 and 2 in the earliest days of web development and have only really returned to pure Symfony now, only otherwise using it when handled by Drupal 8 and Laravel, so this is an area where I'd greatly appreciate your input and to see how this could be amended to handle both in the most Symfony-like way possible.

My instinct would be some sort of switch, whereby detecting which one is in use points to a different function (where we could have a new one for 5.0).

As you're on the core team, I'd be keen to see what your suggestion would be.

Thanks in advance.

**Comment by Nyholm** [comment]
This is not Symfony related. But I will try to explain it a bit better: 

Our `SSOToken` extends `AbstractToken`, is from an other library. (symfony/security-core). That library has updated it major version, ie possible BC breaks. 

4.4 looks like this: 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L165-L182

5.0 looks like this: 
https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L239-L245

As you can see, `AbstractToken::serialize` is final in version 5. (same with unserialize). 

What we need to do is to support both 4.4 and 5.0. Maybe things gets easier if we drop 3.4. 

There is no special "symfony way" of doing this. It is just one class extending another.

**Comment by amharris** [comment]
> This is not Symfony related. But I will try to explain it a bit better:
> 
> Our `SSOToken` extends `AbstractToken`, is from an other library. (symfony/security-core). That library has updated it major version, ie possible BC breaks.
> 
> 4.4 looks like this:
> https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L165-L182
> 
> 5.0 looks like this:
> https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L239-L245
> 
> As you can see, `AbstractToken::serialize` is final in version 5. (same with unserialize).
> 
> What we need to do is to support both 4.4 and 5.0. Maybe things gets easier if we drop 3.4.
> 
> There is no special "symfony way" of doing this. It is just one class extending another.

Ah, thanks.

Firstly, when you say "final," do you mean deprecated?

It's my first time implementing Auth0 and SSO in general, so I've been cutting my teeth on the implementation and haven't really got stuck in with how pure Symfony operates under the bonnet just  yet. 🙂 

I'd love to get to grips with this by tackling the problem.  If you're able to spare the time, would you mind pinging me directly and fleshing out the details and concepts that would help me to understand how I should tackle this appropriately?

**Comment by Nyholm** [comment]
Fixed in #29

**Pull request closed without merging**
