### PR TITLE
Prepare release 0.8.0

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @amenophis are we ready for 0.8.0?

**Comment by amenophis** [comment]
I will check if I need something else.
Also, maybe wait for auth0-php 8.0.0 stable ?

**Comment by Nyholm** [comment]
I thought we could release 1.0 with the sdk’s 8.0. 

Maybe we should add something smart in our composer’s “conflicts”.

**Comment by Nyholm** [comment]
I tested my app (in prod obviously) and I found one small issue #59

**Pull request merged**
